### PR TITLE
Update deps plus update to Elixir 1.16

### PR DESCRIPTION
**Pull request by iperks**
Having issues here, there seem to be cyclic module deps. Not sure how to unwind.

### CODE REVIEW

**Comment by geofflane** [comment]
We really need to come up with a new solution. We forked this because it was abandoned and now we're maintaining it...

**Comment by iperks** [comment]
Agreed. I don’t have a good feel for what it’s supposed to do or whether
there are newer approaches to that problem.

**Comment by geofflane** [comment]
https://github.com/woylie/flop and https://github.com/woylie/flop_phoenix maybe?

**Comment by geofflane** [comment]
Only Molly uses this AFAICT.

**Comment by iperks** [comment]
Closing,

**Comment by iperks** [comment]
See Groot, we moved away from using this to - iirc - using flop

**Pull request closed without merging**
